modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/yourusername/PluralCraft/issues"

[[mods]]
modId="pluralcraft"
version="${file.jarVersion}"
displayName="PluralCraft"
updateJSONURL=""
displayURL="https://github.com/yourusername/PluralCraft"
logoFile=""
credits="Created for DID systems to express themselves in Minecraft"
authors="PluralCraft Team"
description='''
A Minecraft mod designed to allow DID systems to properly express themselves in-game.
Switch between alters, customize profiles, and show your authentic self!
'''

# SUPER IMPORTANT FOR MODS OPTIMIZER!
# This tells the game what sides this mod works on
[[dependencies.pluralcraft]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pluralcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
